### ISSUE TITLE
Can't build with panel 4.15

### ISSUE THREAD

**Issue by jolupa** [equeim/xfce4-alsa-plugin#5]
I know is beta, but can't build with the xfce panel 4.15 any hint?
This is the error I have when building:
```
Found ninja-1.10.0 at /usr/bin/ninja
+ DESTDIR=/home/pkgmk/work/xfce4-alsa-plugin/pkg
+ ninja -C build install
ninja: Entering directory `build'
[2/10] Compiling Vala source ../src/alsamanager.vala ../src/set...ton.vala ../src/volumepopup.vala ../src/xfce4-alsa-plugin.vala.
FAILED: alsa@sha/src/alsamanager.c alsa@sha/src/settings.c alsa@sha/src/settingsdialog.c alsa@sha/src/volumebutton.c alsa@sha/src/volumepopup.c alsa@sha/src/xfce4-alsa-plugin.c alsa.h alsa.vapi 
valac -C --debug --debug --vapidir /home/pkgmk/work/xfce4-alsa-plugin/src/xfce4-alsa-plugin-0.2.1/src/vapi --define=GTK3 --define=XFCE4_13 --pkg gtk+-3.0 --pkg libxfce4panel-2.0 /home/pkgmk/work/xfce4-alsa-plugin/src/xfce4-alsa-plugin-0.2.1/src/vapi/config.vapi /home/pkgmk/work/xfce4-alsa-plugin/src/xfce4-alsa-plugin-0.2.1/src/vapi/gdkkeysyms-2.0.vapi --pkg alsa --color=always --directory alsa@sha --basedir ../ --library alsa --header alsa.h --vapi ../alsa.vapi ../src/alsamanager.vala ../src/settings.vala ../src/settingsdialog.vala ../src/volumebutton.vala ../src/volumepopup.vala ../src/xfce4-alsa-plugin.vala
libxfce4panel-2.0.vapi:124.3-124.41: error: overriding method `Xfce.PanelPlugin.remote_event' is incompatible with base method `bool Xfce.PanelPluginProvider.remote_event (string, GLib.Value, uint)': too few parameters.
		public virtual signal bool remote_event (string name, GLib.Value value);
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```
Thanks.

**Comment by Mizux** [comment]
Seems prototype have changed to:
https://github.com/xfce-mirror/xfce4-panel/blob/6167134972750d147fb97fb8963032bbfa8cdfa2/libxfce4panel/xfce-panel-plugin.h#L125

**Comment by motor-glider** [comment]
Patch for correcting function signature
[xfce4-alsa-plugin-remote_event.patch.gz](https://github.com/equeim/xfce4-alsa-plugin/files/4724982/xfce4-alsa-plugin-remote_event.patch.gz)
